### ISSUE TITLE
collect all the data needed for the project

### ISSUE THREAD

**Issue by Helius-18** [Helius-18/Crop-prediction-and-analysis#1]
whether data should be collected from [`telangana open data`](https://data.telangana.gov.in/dataset/telangana-rainfall-data-2016/resource/9b510b8f-1c4c-4a5a-8244-417dbc9c68a1#{query:{from:100}})

Soil health data should be collcted from [`soil health card`](https://soilhealth.dac.gov.in/PublicReports/NutrientStatusFarmerWise)

**Comment by GiyyarVishalBharadwaj** [comment]
[Uploading 2018_daily_complete_weather_data_0.csv…]()

**Comment by GiyyarVishalBharadwaj** [comment]
https://drive.google.com/drive/folders/1mj101KgqP9735XqwxnX84aVhhOXf-j1Q?usp=sharing
telangana weather data 2018-2022

**Comment by NishithaKoudagani** [comment]
Soil data Warangal rural district(6 mandal's data)
[WarangalRural.zip](https://github.com/Helius-18/Crop-prediction-and-analysis/files/10033497/WarangalRural.zip)

**Comment by NishithaKoudagani** [comment]
soil data Warangal rural(6 mandal's data in excel format)
[WarangalRural(Excel).zip](https://github.com/Helius-18/Crop-prediction-and-analysis/files/10046348/WarangalRural.Excel.zip)
